In [1]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_7ab71323e0c845848c6538065b029102 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='e_er6aA2CV7zSZE7qDXKqmKey9UgpWcLV9CklgzvIhU6',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_7ab71323e0c845848c6538065b029102.get_object(Bucket='predictingdiabetesmellitus-donotdelete-pr-gyrdht5gskzolz',Key='diabetes.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()

import numpy as np
import pandas as pd

In [2]:
#dataset=pd.read_csv("C:/Users/Suguna Simhadri/Desktop/diabetes.csv")

In [3]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
dataset.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                     False
dtype: bool

In [5]:
x=dataset.iloc[:,:8]
y=dataset.iloc[:,8]

In [6]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [7]:
type(x)

pandas.core.frame.DataFrame

In [8]:
y

0      1
1      0
2      1
3      0
4      1
5      0
6      1
7      0
8      1
9      1
10     0
11     1
12     0
13     1
14     1
15     1
16     1
17     1
18     0
19     1
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     0
28     0
29     0
      ..
738    0
739    1
740    1
741    0
742    0
743    1
744    0
745    0
746    1
747    0
748    1
749    1
750    1
751    0
752    0
753    1
754    1
755    1
756    0
757    1
758    0
759    1
760    0
761    1
762    0
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [9]:
type(y)

pandas.core.series.Series

In [10]:
x=dataset.iloc[:,:8].values
y=dataset.iloc[:,8].values

In [11]:
x

array([[   6.   ,  148.   ,   72.   , ...,   33.6  ,    0.627,   50.   ],
       [   1.   ,   85.   ,   66.   , ...,   26.6  ,    0.351,   31.   ],
       [   8.   ,  183.   ,   64.   , ...,   23.3  ,    0.672,   32.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,   26.2  ,    0.245,   30.   ],
       [   1.   ,  126.   ,   60.   , ...,   30.1  ,    0.349,   47.   ],
       [   1.   ,   93.   ,   70.   , ...,   30.4  ,    0.315,   23.   ]])

In [12]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1,

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [14]:
x_train

array([[  0.00000000e+00,   1.51000000e+02,   9.00000000e+01, ...,
          4.21000000e+01,   3.71000000e-01,   2.10000000e+01],
       [  1.00000000e+00,   8.30000000e+01,   6.80000000e+01, ...,
          1.82000000e+01,   6.24000000e-01,   2.70000000e+01],
       [  2.00000000e+00,   1.22000000e+02,   7.00000000e+01, ...,
          3.68000000e+01,   3.40000000e-01,   2.70000000e+01],
       ..., 
       [  4.00000000e+00,   9.40000000e+01,   6.50000000e+01, ...,
          2.47000000e+01,   1.48000000e-01,   2.10000000e+01],
       [  1.10000000e+01,   8.50000000e+01,   7.40000000e+01, ...,
          3.01000000e+01,   3.00000000e-01,   3.50000000e+01],
       [  5.00000000e+00,   1.36000000e+02,   8.20000000e+01, ...,
          0.00000000e+00,   6.40000000e-01,   6.90000000e+01]])

In [15]:
x_train.shape

(537, 8)

In [16]:
x_test

array([[  1.00000000e+00,   1.99000000e+02,   7.60000000e+01, ...,
          4.29000000e+01,   1.39400000e+00,   2.20000000e+01],
       [  2.00000000e+00,   1.07000000e+02,   7.40000000e+01, ...,
          3.36000000e+01,   4.04000000e-01,   2.30000000e+01],
       [  4.00000000e+00,   7.60000000e+01,   6.20000000e+01, ...,
          3.40000000e+01,   3.91000000e-01,   2.50000000e+01],
       ..., 
       [  1.00000000e+00,   9.50000000e+01,   6.00000000e+01, ...,
          2.39000000e+01,   2.60000000e-01,   2.20000000e+01],
       [  1.00000000e+00,   1.06000000e+02,   7.60000000e+01, ...,
          3.75000000e+01,   1.97000000e-01,   2.60000000e+01],
       [  1.00000000e+01,   1.22000000e+02,   7.80000000e+01, ...,
          2.76000000e+01,   5.12000000e-01,   4.50000000e+01]])

In [17]:
x_test.shape

(231, 8)

In [18]:
x.shape

(768, 8)

In [19]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0,

In [20]:
y_train.shape

(537,)

In [21]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0])

In [22]:
y_test.shape

(231,)

In [23]:
y.shape

(768,)

In [24]:
import keras 
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using TensorFlow backend.


# adding layers

In [25]:
model =Sequential()

In [26]:
model.add(Dense(12,input_dim=8,activation='relu')) #input layer

In [27]:
model.add(Dense(15,activation='relu'))

In [28]:
model.add(Dense(8,activation='relu'))

In [29]:
model.add(Dense(10,activation='relu'))

In [30]:
model.add(Dense(1,activation='sigmoid'))  #output layer

# compile

In [31]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [32]:
model.fit(x,y,epochs=100,batch_size=10)

Epoch 1/100
768/768 [==============================] - 0s 577us/step - loss: 2.2553 - acc: 0.5781
Epoch 2/100
768/768 [==============================] - 0s 496us/step - loss: 0.8212 - acc: 0.5729
Epoch 3/100
768/768 [==============================] - 0s 415us/step - loss: 0.7013 - acc: 0.6133
Epoch 4/100
768/768 [==============================] - 0s 504us/step - loss: 0.6600 - acc: 0.6289
Epoch 5/100
768/768 [==============================] - 0s 507us/step - loss: 0.6540 - acc: 0.6458 0s - loss: 0.6162 - acc: 0.
Epoch 6/100
768/768 [==============================] - 0s 513us/step - loss: 0.6545 - acc: 0.6302
Epoch 7/100
768/768 [==============================] - 0s 421us/step - loss: 0.6269 - acc: 0.6680
Epoch 8/100
768/768 [==============================] - 0s 516us/step - loss: 0.6258 - acc: 0.6471
Epoch 9/100
768/768 [==============================] - 0s 511us/step - loss: 0.6297 - acc: 0.6615
Epoch 10/100
768/768 [==============================] - 0s 509us/step - loss: 0.6211 - acc

In [52]:
model.save("diabetes.h5")

In [53]:
get_ipython().system(u'tar -zcvf diabetes.tgz diabetes.h5')

diabetes.h5


In [54]:
y_pred=model.predict(x_test)

In [55]:
y_pred

array([[  9.63646710e-01],
       [  1.87043205e-01],
       [  1.79022416e-01],
       [  6.95937693e-01],
       [  1.90670684e-01],
       [  9.11543518e-02],
       [  6.76368415e-01],
       [  6.50336206e-01],
       [  3.88072908e-01],
       [  4.19574678e-01],
       [  5.80792367e-01],
       [  8.56012523e-01],
       [  2.39471555e-01],
       [  1.72388673e-01],
       [  1.84012160e-01],
       [  2.09448233e-01],
       [  7.35896051e-01],
       [  1.02138549e-01],
       [  4.73548353e-01],
       [  2.79486448e-01],
       [  6.75839543e-01],
       [  3.92315954e-01],
       [  4.77433175e-01],
       [  1.45623103e-01],
       [  1.17594600e-01],
       [  5.63253284e-01],
       [  4.20804024e-02],
       [  6.83258712e-01],
       [  2.27865785e-01],
       [  3.60889524e-01],
       [  5.16117990e-01],
       [  2.12922618e-01],
       [  8.57473612e-02],
       [  5.44237912e-01],
       [  1.41494602e-01],
       [  8.53380024e-01],
       [  5.46181321e-01],
 

In [56]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0])

In [57]:
y_pred1 = model.predict(np.array([[5,116,74,0,0,25.6,0.201,30]]))

In [58]:
y_pred1

array([[ 0.30298603]], dtype=float32)

In [59]:
y_pred2 =model.predict(np.array([[15,136,70,32,110,37.1,0.153,43]]))

In [60]:
y_pred2

array([[ 0.5958547]], dtype=float32)

In [61]:
y_pred3 = model.predict(np.array([[0,125,96,0,0,22.5,0.262,21]]))

In [62]:
y_pred3

array([[ 0.00112301]], dtype=float32)

In [63]:
y_pred4 = model.predict(np.array([[8,179,72,42,130,32.7,0.719,36]]))

In [64]:
y_pred4

array([[ 0.73589605]], dtype=float32)

In [65]:
y_pred5 = model.predict(np.array([[11,103,68,40,0,46.2,0.126,42]]))

In [45]:
y_pred5

array([[ 0.62086201]], dtype=float32)

In [66]:
!pip install watson_machine_learning_client

tensorflow 1.3.0 requires tensorflow-tensorboard<0.2.0,>=0.1.0, which is not installed.


In [67]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [68]:
wml_credentials={
  "url": "https://eu-gb.ml.cloud.ibm.com",
  "access_key": "vQu_BmYuF_HCKo797yKIJkxnJ5hR44VbWjV5xhbfEwsr",
  "username": "262c188e-30f5-4a70-88c7-cf1c408fc458",
  "password": "ff336350-39da-459e-bfa9-a13ef5f4ada4",
  "instance_id": "2bac0398-06d5-4634-9514-d2dd7f443b41"
}

In [69]:
client = WatsonMachineLearningAPIClient( wml_credentials )

In [70]:
metadata = {
    client.repository.ModelMetaNames.NAME: "keras model",
    client.repository.ModelMetaNames.FRAMEWORK_NAME: "tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES:[{'name':'keras','version':'2.1.3'}],
    client.repository.ModelMetaNames.FRAMEWORK_VERSION: "1.5"
}


In [71]:
model_details = client.repository.store_model( model="diabetes.tgz", meta_props=metadata )

In [72]:
model_id=model_details["metadata"]["guid"]

In [74]:
model_deployment_details = client.deployments.create(artifact_uid=model_id,name='deployment')



#######################################################################################

Synchronous deployment creation for uid: '469dd45a-a23e-48f4-95ae-44696564fd18' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='fed96a46-f7b9-4ac2-a792-a2c638ed6ce6'
------------------------------------------------------------------------------------------------




In [75]:
scoring_endpoint=client.deployments.get_scoring_url(model_deployment_details)

In [76]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/2bac0398-06d5-4634-9514-d2dd7f443b41/deployments/fed96a46-f7b9-4ac2-a792-a2c638ed6ce6/online'

In [77]:
scoring_payload = {"fields":["Prediction"],"values":[[6,148,72,35,0,33.6,0.627,50]]}

In [78]:
predictions = client.deployments.score(scoring_endpoint,scoring_payload)

In [79]:
predictions

{'fields': ['prediction', 'prediction_classes', 'probability'],
 'values': [[[0.8781336545944214], [1], [0.8781336545944214]]]}